CREATE TABLE IF NOT EXISTS distribution_runs (
  id TEXT PRIMARY KEY,
  period_key TEXT NOT NULL,
  collection_address TEXT NOT NULL,
  property_id TEXT NOT NULL REFERENCES marketplace_entries(id) ON DELETE RESTRICT,
  period_start_at TIMESTAMPTZ NOT NULL,
  period_end_at TIMESTAMPTZ NOT NULL,
  period_timezone TEXT NOT NULL DEFAULT 'America/Bogota',
  policy_version TEXT NOT NULL,
  token_mint TEXT NOT NULL,
  total_amount_minor BIGINT NOT NULL CHECK (total_amount_minor >= 0),
  status TEXT NOT NULL CHECK (status IN ('draft', 'blocked', 'finalized', 'failed')),
  blocked_reason TEXT,
  output_checksum TEXT,
  item_count INTEGER NOT NULL DEFAULT 0 CHECK (item_count >= 0),
  total_wallets INTEGER NOT NULL DEFAULT 0 CHECK (total_wallets >= 0),
  created_by_actor_id TEXT NOT NULL,
  finalized_by_actor_id TEXT,
  finalized_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (period_end_at > period_start_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS distribution_runs_scope_policy_uidx
  ON distribution_runs (period_key, policy_version, collection_address, property_id);

CREATE INDEX IF NOT EXISTS distribution_runs_status_created_idx
  ON distribution_runs (status, created_at DESC);

CREATE INDEX IF NOT EXISTS distribution_runs_scope_period_idx
  ON distribution_runs (collection_address, property_id, period_start_at DESC);

CREATE TABLE IF NOT EXISTS distribution_items (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES distribution_runs(id) ON DELETE CASCADE,
  wallet_public_key TEXT NOT NULL,
  asset_address TEXT,
  frozen_seconds BIGINT NOT NULL CHECK (frozen_seconds >= 0),
  amount_minor BIGINT NOT NULL CHECK (amount_minor >= 0),
  rounding_remainder_rank INTEGER,
  exclusion_reason TEXT,
  item_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS distribution_items_run_wallet_idx
  ON distribution_items (run_id, wallet_public_key);

CREATE INDEX IF NOT EXISTS distribution_items_run_amount_idx
  ON distribution_items (run_id, amount_minor DESC);

CREATE TABLE IF NOT EXISTS distribution_audit_events (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES distribution_runs(id) ON DELETE CASCADE,
  event_name TEXT NOT NULL,
  actor_type TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  event_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS distribution_audit_events_run_created_idx
  ON distribution_audit_events (run_id, created_at ASC);

CREATE OR REPLACE FUNCTION prevent_finalized_distribution_run_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.status = 'finalized' THEN
    RAISE EXCEPTION 'Finalized distribution runs are immutable.';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS distribution_runs_prevent_finalized_update ON distribution_runs;
CREATE TRIGGER distribution_runs_prevent_finalized_update
BEFORE UPDATE ON distribution_runs
FOR EACH ROW
EXECUTE FUNCTION prevent_finalized_distribution_run_mutation();

DROP TRIGGER IF EXISTS distribution_runs_set_updated_at ON distribution_runs;
CREATE TRIGGER distribution_runs_set_updated_at
BEFORE UPDATE ON distribution_runs
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_column();

COMMENT ON TABLE distribution_runs IS
  'Auditable off-chain distribution preparation runs scoped to one BRIDS collection/property and policy version.';

COMMENT ON TABLE distribution_items IS
  'Prepared wallet and asset distribution rows generated by the deterministic calculation engine.';

COMMENT ON TABLE distribution_audit_events IS
  'Append-only audit trail for distribution run lifecycle events and blocking reasons.';
