import type { DocumentType } from "./types";

export interface CanonicalRouteInput {
  slug: string;
  type: DocumentType;
}

export interface CanonicalRouteEntry extends CanonicalRouteInput {
  path: string;
}

export function getCanonicalPathForDocument({ slug, type }: CanonicalRouteInput): string {
  switch (type) {
    case "institutional-page":
      return `/${slug}`;
    case "article":
      return `/knowledge/articles/${slug}`;
    case "knowledge-base":
      return `/knowledge/${slug}`;
    case "faq":
      return `/knowledge/faq/${slug}`;
    case "glossary-term":
      return `/knowledge/definitions/${slug}`;
    case "changelog":
      return `/resources/${slug}`;
    default: {
      const exhaustiveCheck: never = type;
      throw new Error(`Unsupported document type for route mapping: ${String(exhaustiveCheck)}`);
    }
  }
}

export function buildCanonicalRoutes(entries: CanonicalRouteInput[]): CanonicalRouteEntry[] {
  return entries.map((entry) => ({
    ...entry,
    path: getCanonicalPathForDocument(entry)
  }));
}

export function assertNoCanonicalRouteCollisions(entries: CanonicalRouteInput[]): void {
  const routes = buildCanonicalRoutes(entries);
  const seen = new Map<string, CanonicalRouteEntry>();

  for (const entry of routes) {
    const existing = seen.get(entry.path);
    if (existing) {
      throw new Error(
        `Canonical route collision: "${entry.path}" generated by ${existing.type}:${existing.slug} and ${entry.type}:${entry.slug}`
      );
    }
    seen.set(entry.path, entry);
  }
}

export interface BreadcrumbItem {
  label: string;
  href: string;
}

export function buildKnowledgeBreadcrumbs(current: BreadcrumbItem): BreadcrumbItem[] {
  return [
    { label: "Home", href: "/" },
    { label: "Knowledge", href: "/knowledge" },
    current
  ];
}
