import { describe, test, expect } from 'vitest';
import path from 'path';
import fs from 'fs';

describe('09 - Monorepo FDD Architecture & Governance Harness (BRI-186)', () => {
  const repoRoot = path.resolve(__dirname, '../../../');
  const workspaceConfig = path.join(repoRoot, 'pnpm-workspace.yaml');
  const webAppRoot = path.join(repoRoot, 'apps/web');
  const featuresRoot = path.join(webAppRoot, 'src/features');
  const appRoutesRoot = path.join(webAppRoot, 'src/app');

  // List of all 16 canonical vertical feature slices
  const expectedFeatureSlices = [
    'landing',
    'marketplace',
    'checkout-payment',
    'recurring-deposits',
    'offline-recovery',
    'profile',
    'investor-portfolio',
    'referral-marketing',
    'educational-resources',
    'pwa-notifications',
    'admin',
    'property-management',
    'staking-distribution',
    'nft-minting',
    'asset-freeze-control',
    'transparency-portal',
  ];

  describe('1. Monorepo Workspaces & Root Structure', () => {
    test('pnpm-workspace.yaml exists and configures monorepo workspaces', () => {
      expect(fs.existsSync(workspaceConfig)).toBe(true);
      const content = fs.readFileSync(workspaceConfig, 'utf8');
      expect(content).toContain('apps/web');
      expect(content).toContain('packages/*');
    });

    test('apps/web directory exists as Next.js app package', () => {
      expect(fs.existsSync(webAppRoot)).toBe(true);
      expect(fs.existsSync(path.join(webAppRoot, 'package.json'))).toBe(true);
    });

    test('packages/solana-client package exists for autogenerated IDL types', () => {
      const solanaClientPkg = path.join(repoRoot, 'packages/solana-client');
      expect(fs.existsSync(solanaClientPkg)).toBe(true);
      expect(fs.existsSync(path.join(solanaClientPkg, 'package.json'))).toBe(true);
    });
  });

  describe('2. Vertical Feature Slices & Public API Boundaries (index.ts)', () => {
    test('src/features root directory exists', () => {
      expect(fs.existsSync(featuresRoot)).toBe(true);
    });

    expectedFeatureSlices.forEach(slice => {
      test(`feature slice "${slice}" exists and exports a valid Public API (index.ts)`, () => {
        const sliceDir = path.join(featuresRoot, slice);
        const indexPath = path.join(sliceDir, 'index.ts');

        expect(fs.existsSync(sliceDir)).toBe(true);
        expect(fs.existsSync(indexPath)).toBe(true);
      });

      test(`feature slice "${slice}" implements 4-Layer Functional Architecture`, () => {
        const sliceDir = path.join(featuresRoot, slice);
        const presentationDir = path.join(sliceDir, 'presentation');
        const applicationDir = path.join(sliceDir, 'application');
        const domainDir = path.join(sliceDir, 'domain');
        const infrastructureDir = path.join(sliceDir, 'infrastructure');

        expect(fs.existsSync(presentationDir)).toBe(true);
        expect(fs.existsSync(applicationDir)).toBe(true);
        expect(fs.existsSync(domainDir)).toBe(true);
        expect(fs.existsSync(infrastructureDir)).toBe(true);
      });
    });
  });

  describe('3. Shared Cross-Cutting Modules & Sub-Structures', () => {
    const sharedRoot = path.join(featuresRoot, 'shared');

    test('src/features/shared exists and exports index.ts', () => {
      expect(fs.existsSync(sharedRoot)).toBe(true);
      expect(fs.existsSync(path.join(sharedRoot, 'index.ts'))).toBe(true);
    });

    test('shared/auth contains siws, workos, reconciliation, and rbac sub-modules', () => {
      const authRoot = path.join(sharedRoot, 'auth');
      expect(fs.existsSync(path.join(authRoot, 'siws'))).toBe(true);
      expect(fs.existsSync(path.join(authRoot, 'workos'))).toBe(true);
      expect(fs.existsSync(path.join(authRoot, 'reconciliation'))).toBe(true);
      expect(fs.existsSync(path.join(authRoot, 'rbac'))).toBe(true);
    });

    test('shared/infrastructure contains db, solana-rpc, squads, metaplex, and ipfs', () => {
      const infraRoot = path.join(sharedRoot, 'infrastructure');
      expect(fs.existsSync(path.join(infraRoot, 'db'))).toBe(true);
      expect(fs.existsSync(path.join(infraRoot, 'solana-rpc'))).toBe(true);
      expect(fs.existsSync(path.join(infraRoot, 'squads'))).toBe(true);
      expect(fs.existsSync(path.join(infraRoot, 'ipfs'))).toBe(true);

      const metaplexRoot = path.join(infraRoot, 'metaplex');
      expect(fs.existsSync(path.join(metaplexRoot, 'das-fetcher'))).toBe(true);
      expect(fs.existsSync(path.join(metaplexRoot, 'core-writer'))).toBe(true);
    });

    test('shared/ui contains UI kit, ThemeToggle (Dark Mode), and Motion 12 components', () => {
      const uiRoot = path.join(sharedRoot, 'ui');
      expect(fs.existsSync(uiRoot)).toBe(true);
      expect(fs.existsSync(path.join(uiRoot, 'theme-toggle.tsx'))).toBe(true);
    });
  });

  describe('4. Private Route Migration (/protected -> /profile)', () => {
    test('routes use /profile naming and legacy /protected is removed', () => {
      const profileRoute = path.join(appRoutesRoot, 'profile');
      const protectedRoute = path.join(appRoutesRoot, 'protected');

      expect(fs.existsSync(profileRoute)).toBe(true);
      expect(fs.existsSync(protectedRoute)).toBe(false);

      expect(fs.existsSync(path.join(profileRoute, 'perfil'))).toBe(true);
      expect(fs.existsSync(path.join(profileRoute, 'portfolio'))).toBe(true);
      expect(fs.existsSync(path.join(profileRoute, 'referrals'))).toBe(true);
    });
  });

  describe('5. Strict Governance & Layer Isolation Rules', () => {
    test('no presentation components directly import database or solana RPC clients', () => {
      if (!fs.existsSync(featuresRoot)) return;

      function scanDirForViolations(dirPath: string) {
        const files = fs.readdirSync(dirPath, { withFileTypes: true });
        for (const file of files) {
          const fullPath = path.join(dirPath, file.name);
          if (file.isDirectory()) {
            if (file.name === 'presentation') {
              const presFiles = fs.readdirSync(fullPath, { recursive: true });
              for (const pf of presFiles) {
                const pfPath = path.join(fullPath, String(pf));
                if (fs.statSync(pfPath).isFile() && (pfPath.endsWith('.ts') || pfPath.endsWith('.tsx'))) {
                  const content = fs.readFileSync(pfPath, 'utf8');
                  expect(content).not.toContain('@/lib/db');
                  expect(content).not.toContain('@solana/web3.js');
                  expect(content).not.toContain('infrastructure/db');
                }
              }
            } else {
              scanDirForViolations(fullPath);
            }
          }
        }
      }

      scanDirForViolations(featuresRoot);
    });
  });

  describe('6. Legacy Proxies, Symlinks & Directory Elimination', () => {
    test('no root symlinks exist in the repository', () => {
      const symlinkCandidates = [
        path.join(repoRoot, 'components'),
        path.join(repoRoot, 'public'),
        path.join(repoRoot, 'src'),
        path.join(repoRoot, 'src/features'),
        path.join(repoRoot, 'apps/web/app')
      ];

      for (const candidate of symlinkCandidates) {
        if (fs.existsSync(candidate)) {
          const stats = fs.lstatSync(candidate);
          expect(stats.isSymbolicLink(), `Path ${candidate} must not be a symbolic link`).toBe(false);
        }
      }
    });

    test('legacy component directories are completely eliminated', () => {
      const componentsRoot = path.join(webAppRoot, 'src/components');
      expect(fs.existsSync(path.join(componentsRoot, 'admin'))).toBe(false);
      expect(fs.existsSync(path.join(componentsRoot, 'checkout'))).toBe(false);
      expect(fs.existsSync(path.join(componentsRoot, 'dashboard'))).toBe(false);
      expect(fs.existsSync(path.join(componentsRoot, 'marketplace'))).toBe(false);
      expect(fs.existsSync(path.join(componentsRoot, 'sections'))).toBe(false);
    });

    test('legacy lib proxies are eliminated and replaced by canonical feature modules', () => {
      const libDir = path.join(webAppRoot, 'src/lib');
      const legacyLibProxies = [
        'purchase-service.ts',
        'purchase-anti-bot.ts',
        'purchase-attempts-repository.ts',
        'checkout-service.ts',
        'checkout-repository.ts',
        'core-candy-machine-admin.ts',
        'stake-profile-events-repository.ts',
        'referrals/reward-engine.ts',
        'referrals/payout-service.ts',
        'compliance/aml-screening-service.ts',
        'compliance/case-service.ts',
        'distributions/distribution-engine.ts',
        'claims/claim-flow.ts'
      ];

      for (const proxyFile of legacyLibProxies) {
        expect(fs.existsSync(path.join(libDir, proxyFile))).toBe(false);
      }
    });
  });

  describe('7. TSConfig Path Aliases Harmonization', () => {
    test('tsconfig compiler paths map directly to canonical apps/web/src locations with zero legacy fallbacks', () => {
      const tsconfigPath = path.join(repoRoot, 'tsconfig.json');
      const tsconfig = JSON.parse(fs.readFileSync(tsconfigPath, 'utf8'));

      expect(tsconfig.compilerOptions.paths['@/*']).toEqual(['./apps/web/src/*', './*']);
      expect(tsconfig.compilerOptions.paths['@/features/*']).toEqual(['./apps/web/src/features/*']);
      expect(tsconfig.compilerOptions.paths['@core/*']).toEqual(['./apps/web/src/lib/core/*']);
      expect(tsconfig.compilerOptions.paths['@software/*']).toEqual(['./apps/web/src/lib/software/*']);
      expect(tsconfig.compilerOptions.paths['@knowledge/*']).toEqual(['./apps/web/src/lib/knowledge/*']);
      expect(tsconfig.compilerOptions.paths['@regulatory/*']).toEqual(['./apps/web/src/lib/regulatory/*']);
    });
  });
});
