[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.11"

[features]
resolution = true
skip-lint = false

[programs.devnet]
payout_settlement = "HLp7YXKZZ8uPuzwN3CtuDxtgYoWhc5Fb1FHj5bHEe9zE"
project_config_notary = "HLp7YXKZZ8uPuzwN3CtuDxtgYoWhc5Fb1FHj5bHEe9zE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jaymusicmachine/my-solana-wallet.json"

[scripts]
test = "vitest run tests/programs/payout-settlement.test.ts"
