[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.11"

[features]
resolution = true
skip-lint = false

[programs.devnet]
payout_settlement = "Bin3MC6Fqu5pTc5iMjFUYN4naYFir5fzp7iwGi3ag3iJ"
project_config_notary = "EAwShRn1voHtw3MgHEfyw5Svb4Xv1hePNPWQvD8NjvRi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/my-solana-wallet.json"

[scripts]
test = "vitest run tests/programs/payout-settlement.test.ts"
