[toolchain]
anchor_version = "0.31.1"
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.devnet]
payout_settlement = "J2xccRtuG43drESLYznHhLhQkLTdfepcKYbiQ9BsJVaf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "vitest run tests/programs/payout-settlement.test.ts"
