import { ReasoningResult, ReasoningTrace } from "./types";
import { readdir, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

export interface KnowledgeReasoningPlanEntry {
  id: string;
  title: string;
  status: "observed";
  kind: "reasoning-plan";
  promotionTarget: "automation";
  scope: string;
  filePath: string;
  owner: string;
  createdAt: string;
  updatedAt: string;
  sourceIssue: string;
  sourceFeature: string;
  enforcementCandidate: string;
  reasoningTrace: ReasoningTrace;
  task: string;
  domain: string;
  model: string;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export async function storeReasoningPlan(
  result: ReasoningResult,
  task: string,
  domain: string,
  model: string,
  issueKey: string = "BRI-177",
  featureSlug: string = "business-logic-reasoner"
): Promise<string> {
  const knowledgeDir = path.join(process.cwd(), "docs", "knowledge", "reasoning-plans");
  await mkdir(knowledgeDir, { recursive: true });

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const taskSlug = slugify(task).slice(0, 50);
  const fileName = `REASONING-PLAN-${timestamp}-${taskSlug}.md`;
  const filePath = path.join(knowledgeDir, fileName);

  const trace = result.trace;
  const frontmatter = {
    id: `REASONING-PLAN-${timestamp}-${taskSlug}`,
    title: `Reasoning Plan: ${task}`,
    status: "observed",
    kind: "reasoning-plan",
    promotion_target: "automation",
    scope: "shared",
    file_path: `docs/knowledge/reasoning-plans/${fileName}`,
    owner: "reasoning-agent",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    source_issue: issueKey,
    source_feature: featureSlug,
    enforcement_candidate: "no",
  };

  const selectedModulesMd = trace.select.selectedModules
    .map((m, i) => `${i + 1}. [${trace.select.selectedIds[i]}] ${m}`)
    .join("\n");

  const adaptedModulesMd = trace.adapt.adaptedModules
    .map((m, i) => `${i + 1}. **${m.original}**\n   → ${m.adapted}`)
    .join("\n\n");

  const planStepsMd = trace.implement.planSteps
    .map((s) => `${s.stepNumber}. ${s.description}\n   Expected: ${s.expectedOutput}`)
    .join("\n\n");

  const stepOutputsMd = trace.solve.stepOutputs
    .map((out, i) => `${i + 1}. ${out}`)
    .join("\n\n");

  const content = `---
id: ${frontmatter.id}
title: "${frontmatter.title}"
status: ${frontmatter.status}
kind: ${frontmatter.kind}
promotion_target: ${frontmatter.promotionTarget}
scope: ${frontmatter.scope}
filePath: ${frontmatter.file_path}
owner: ${frontmatter.owner}
created_at: ${frontmatter.created_at}
updated_at: ${frontmatter.updated_at}
source_issue: ${frontmatter.sourceIssue}
source_feature: ${frontmatter.sourceFeature}
enforcement_candidate: ${frontmatter.enforcementCandidate}
---

# Reasoning Plan: ${task}

**Domain:** ${domain}  
**Model:** ${model}  
**Issue:** ${issueKey}  
**Feature:** ${featureSlug}  
**Generated:** ${frontmatter.created_at}

## Task
${task}

## SELECT Stage
**Selected Modules:** [${trace.select.selectedIds.join(", ")}]  
**Rationale:** ${trace.select.selectionRationale}

### Modules
${selectedModulesMd}

## ADAPT Stage
### Adapted Modules
${adaptedModulesMd}

## IMPLEMENT Stage
**Final Answer Format:** ${trace.implement.finalAnswerFormat}

### Plan Steps
${planStepsMd}

## SOLVE Stage
### Step Outputs
${stepOutputsMd}

### Final Answer
${result.answer}

---

*Generated by Self-Discover Reasoning Agent (Zhou et al., Google DeepMind 2024)*
`;

  await writeFile(filePath, content, "utf-8");
  return filePath;
}

export async function listReasoningPlans(): Promise<string[]> {
  const knowledgeDir = path.join(process.cwd(), "docs", "knowledge", "reasoning-plans");
  try {
    const entries = await readdir(knowledgeDir, { withFileTypes: true });
    return entries
      .filter((e) => e.isFile() && e.name.endsWith(".md"))
      .map((e) => path.join(knowledgeDir, e.name))
      .sort()
      .reverse();
  } catch {
    return [];
  }
}