import { ReasoningResult, ReasoningTrace, PlanStep } from "./types";

export interface LinearSlicePlan {
  slices: Array<{
    id: string;
    slug: string;
    type: "spec" | "delivery";
    description: string;
    workflow: string[];
    dependsOn: string[];
  }>;
  parentIssue: string;
  featureSlug: string;
}

export function generateLinearSlicePlan(
  result: ReasoningResult,
  task: string,
  issueKey: string,
  featureSlug: string
): LinearSlicePlan {
  const trace = result.trace;
  const planSteps = trace.implement.planSteps;

  const slices = [
    {
      id: "S01",
      slug: "spec-architecture",
      type: "spec" as const,
      description: "Architecture, contracts, module library, domain adaptation design",
      workflow: ["frontend-cycle", "docs"],
      dependsOn: [],
    },
    {
      id: "S02",
      slug: "core-engine",
      type: "delivery" as const,
      description: "Core engine: SELECT/ADAPT/IMPLEMENT/SOLVE pipeline with structured output",
      workflow: ["frontend-cycle", "reviewer"],
      dependsOn: ["S01"],
    },
    {
      id: "S03",
      slug: "domain-adapters",
      type: "delivery" as const,
      description: "Domain adapters for ADAPT stage: Solana, NFT/Metaplex, Compliance",
      workflow: ["frontend-cycle", "blockchain-cycle"],
      dependsOn: ["S01", "S02"],
    },
    {
      id: "S04",
      slug: "cli-invocation",
      type: "delivery" as const,
      description: "CLI tool: reasoning-agent \"task\" + library export",
      workflow: ["frontend-cycle"],
      dependsOn: ["S01", "S02"],
    },
    {
      id: "S05",
      slug: "workflow-integration",
      type: "delivery" as const,
      description: "Workflow hooks: task-init.sh --reasoning-agent, Linear slice planner, knowledge system",
      workflow: ["frontend-cycle", "docs"],
      dependsOn: ["S01", "S02", "S04"],
    },
    {
      id: "S06",
      slug: "validation-gates",
      type: "delivery" as const,
      description: "Validation gates: test-first pipeline, Solana MCP validation, human review workflow",
      workflow: ["reviewer", "qa"],
      dependsOn: ["S01-S05"],
    },
  ];

  return {
    slices,
    parentIssue: issueKey,
    featureSlug,
  };
}

export function formatLinearSlicePlan(plan: LinearSlicePlan): string {
  const lines = [
    `# Linear Slice Plan for ${plan.featureSlug}`,
    "",
    `**Parent Issue:** ${plan.parentIssue}`,
    `**Feature:** ${plan.featureSlug}`,
    "",
    "## Slices",
    "",
    "| Slice | Type | Slug | Description | Workflow | Depends On |",
    "|-------|------|------|-------------|----------|------------|",
  ];

  for (const slice of plan.slices) {
    lines.push(
      `| ${slice.id} | ${slice.type} | ${slice.slug} | ${slice.description} | ${slice.workflow.join(", ")} | ${slice.dependsOn.join(", ")} |`
    );
  }

  lines.push("");
  lines.push("---");
  lines.push("*Generated by Self-Discover Reasoning Agent*");

  return lines.join("\n");
}

export async function createLinearIssues(plan: LinearSlicePlan): Promise<void> {
  console.log("Linear slice plan generated. Use Linear CLI or UI to create issues.");
  console.log(formatLinearSlicePlan(plan));
}